# Generated by Django 6.0.1 on 2026-01-28 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='create_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='author',
            new_name='author_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='create_time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='author',
        ),
        migrations.AddField(
            model_name='answer',
            name='author_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
